apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yeucj4isz-nodejs 
  janus-idp.io/tekton: yeucj4isz-nodejs
  backstage.io/kubernetes-id: yeucj4isz-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yeucj4isz-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml